*this program creates the cash;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.capxraw;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(che);
if not missing(nyear);
if not missing(gvkey2);
if not missing(at);
if not missing(capx);
if (at-che)=0 then delete;
keep gvkey2  cusip nyear che at capx;
proc sort nodupkey; by gvkey2 nyear;
data a2; set a1;
capx2=capx/(at-che);
if capx2 ne ".";
if nyear>=1975;
data a3; set a2;
keep gvkey2 cusip nyear capx2;
proc sort nodupkey; by gvkey2 nyear;
data a4; set a3;
data tmp1.capxall1; set a4;
data tmp1.capxall2; set a4;
data tmp1.capxall3; set a4;
data tmp1.capxall4; set a4;
data tmp1.capxall5; set a4;
data tmp1.capxall6; set a4;
data tmp1.capxall7; set a4;
data tmp1.capxall8; set a4;
data tmp1.capxall9; set a4;
data tmp1.capxall10; set a4;
proc means; run;

