*this program creates the cash from operations;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.cforaw;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(che);
if not missing(oancf);
if not missing(nyear);
if not missing(gvkey2);
if not missing(at);
if (at-che)=0 then delete;
keep gvkey2  cusip nyear oancf che at ;
proc sort nodupkey; by gvkey2 nyear;
data a2; set a1;
cfo=oancf/(at-che);
if cfo ne ".";
if nyear>=1975;
data a3; set a2;
keep gvkey2 cusip nyear cfo;
proc sort nodupkey; by gvkey2 nyear;
data a4; set a3;
data tmp1.cfoall1; set a4;
data tmp1.cfoall2; set a4;
data tmp1.cfoall3; set a4;
data tmp1.cfoall4; set a4;
data tmp1.cfoall5; set a4;
data tmp1.cfoall6; set a4;
data tmp1.cfoall7; set a4;
data tmp1.cfoall8; set a4;
data tmp1.cfoall9; set a4;
data tmp1.cfoall10; set a4;
proc means; run;
proc print data=a4 (obs = 500); run;
