*this program creates the cash;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.cashraw;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(che);
if not missing(nyear);
if not missing(gvkey2);
if not missing(at);
if (at-che)=0 then delete;
keep gvkey2  cusip nyear che at ;
proc sort nodupkey; by gvkey2 nyear;
data a2; set a1;
che2=che/(at-che);
if che2 ne ".";
if nyear>=1975;
data a3; set a2;
keep gvkey2 cusip nyear che2;
proc sort nodupkey; by gvkey2 nyear;
data a4; set a3;
data tmp1.cashall1; set a4;
data tmp1.cashall2; set a4;
data tmp1.cashall3; set a4;
data tmp1.cashall4; set a4;
data tmp1.cashall5; set a4;
data tmp1.cashall6; set a4;
data tmp1.cashall7; set a4;
data tmp1.cashall8; set a4;
data tmp1.cashall9; set a4;
data tmp1.cashall10; set a4;
proc means; run;

