*this program creates the Dividend Dummy;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.dvcraw;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(nyear);
if not missing(gvkey2);
if dvc="." then dvc=0;
keep gvkey2 cusip nyear dvc ;
proc sort nodupkey; by gvkey2 nyear;
data a2; set a1;
dvc_dummy = 0;
if not first.gvkey2 and lag(gvkey2)=gvkey2 and lag(dvc)>0 then dvc_dummy=1;
data a3; set a2;
if nyear>=1975;
keep gvkey2 cusip nyear dvc_dummy;
proc sort nodupkey; by gvkey2 nyear;
data a4; set a3;
data tmp1.dvcall1; set a4;
data tmp1.dvcall2; set a4;
data tmp1.dvcall3; set a4;
data tmp1.dvcall4; set a4;
data tmp1.dvcall5; set a4;
data tmp1.dvcall6; set a4;
data tmp1.dvcall7; set a4;
data tmp1.dvcall8; set a4;
data tmp1.dvcall9; set a4;
data tmp1.dvcall10; set a4;
proc means; run;
proc print data=a4 (obs=200); run;
