*this program creates the Interest rates;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.interestraw;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(che);
if not missing(nyear);
if not missing(gvkey2);
if not missing(at);
if not missing(xint);
if not missing(dltt);
if not missing(dlc);
keep gvkey2  cusip nyear che at xint dlc dltt;
proc sort nodupkey; by gvkey2 nyear;
data a2; set a1;
debt = dlc + dltt;
if debt ne 0 then intrate = (xint / debt)*100;
else intrate = .;
if intrate ne ".";
keep gvkey2 cusip nyear intrate at che;
proc sort nodupkey; by gvkey2 nyear;
data a3; set a2;
if (at-che) ne 0 then intrate = intrate/(at-che);
else intrate = .;
if intrate ne ".";
if nyear>=1975;
keep gvkey2 cusip nyear intrate;
proc sort nodupkey; by gvkey2 nyear;
data a4; set a3;
data tmp1.intrate1; set a4;
data tmp1.intrate2; set a4;
data tmp1.intrate3; set a4;
proc means; run;
