libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.samplecriteria;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(che);
if not missing(seq);
if not missing(prcc_c);
if not missing(at);
if not missing(sale);
if not missing(sic);
keep gvkey2 cusip nyear seq prcc_c at che sale sic;
proc sort nodupkey; by gvkey2 nyear;
data a2; set a1;
if prcc_c > 2;
if at > 0;
if sale > 0;
keep gvkey2 cusip nyear seq prcc_c sale at sic che;
proc sort nodupkey; by gvkey2 nyear;
data a3; set a2;
sic2 = int(sic/100);
if not (40<=sic2<=49);
if not (60<=sic2<=67);
keep gvkey2 cusip nyear seq prcc_c sale at sic2 che;
proc sort nodupkey; by gvkey2 nyear;
data tmp1.sampledata1; set a3;
data tmp1.sampledata2; set a3;
data tmp1.sampledata3; set a3;
proc means; run;
