*this program creates the industry sigma;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.sigmaall1;
keep nyear sic2 sigmacash;

data a2; set tmp1.dummiesraw;
data a3; set a2;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(nyear);
if not missing(gvkey2);
if not missing(sic);
proc sort nodupkey; by gvkey2 nyear;
data a4; set a3;
if nyear>=1975;
keep gvkey2 nyear cusip sic;
data a5; set a4;
sic2=int(sic/100);
proc sort; by nyear sic2; 

data a6;
merge a5 a1;
by nyear sic2;
if gvkey2 ne ".";
keep gvkey2 cusip nyear sigmacash;
proc sort nodupkey; by gvkey2 nyear;
data a7; set a6;
data tmp1.indsigmaall1; set a7;
data tmp1.indsigmaall2; set a7;
data tmp1.indsigmaall3; set a7;
data tmp1.indsigmaall4; set a7;
data tmp1.indsigmaall5; set a7;
data tmp1.indsigmaall6; set a7;
data tmp1.indsigmaall7; set a7;
data tmp1.indsigmaall8; set a7;
data tmp1.indsigmaall9; set a7;
data tmp1.indsigmaall10; set a7;
proc print data=a7 (obs=500);
proc means; run;
