*this program creates the Tax burden on Foreign Income;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s10_sea\Downloads\SAS_datacodes';
run;
data a1; set tmp1.tfiraw;
gvkey2=gvkey*1;
nyear=year(datadate);
if not missing(nyear);
if not missing(gvkey2);
if pifo="." then pifo=0;
if txfo="." then txfo=0;
if che="." then delete;
if at="." then delete;
if (at-che)=0 then delete;
keep gvkey2  cusip nyear che at pifo txfo;
proc sort nodupkey; by gvkey2 nyear;
data a2; set a1;
tax = (pifo * 0.35);
tfi=((tax - txfo)/(at-che))*100;
if tax < txfo then tfi=0;
if tfi ne ".";
if nyear>=1975;
data a3; set a2;
keep gvkey2 cusip nyear tfi;
proc sort nodupkey; by gvkey2 nyear;
data a4; set a3;
data tmp1.tfiall1; set a4;
data tmp1.tfiall2; set a4;
data tmp1.tfiall3; set a4;
data tmp1.tfiall4; set a4;
data tmp1.tfiall5; set a4;
data tmp1.tfiall6; set a4;
data tmp1.tfiall7; set a4;
data tmp1.tfiall8; set a4;
data tmp1.tfiall9; set a4;
data tmp1.tfiall10; set a4;
proc means; run;
proc print data=a4 (obs=1000); run;
